services:

    _defaults:
        autoconfigure: true
        autowire:      true

    Jmf\CrudEngine\:
        resource: '../../'

    Jmf\CrudEngine\Controller\CreateAction:
        arguments:
            $container:           '@service_container'
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\CreateActionHelperDefault'
        tags: [ 'controller.service_arguments' ]

    Jmf\CrudEngine\Controller\DeleteAction:
        arguments:
            $container:           '@service_container'
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\DeleteActionHelperDefault'
        tags: [ 'controller.service_arguments' ]

    Jmf\CrudEngine\Controller\IndexAction:
        arguments:
            $container:           '@service_container'
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\IndexActionHelperDefault'
        tags: [ 'controller.service_arguments' ]

    Jmf\CrudEngine\Controller\ReadAction:
        arguments:
            $container:           '@service_container'
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\ReadActionHelperDefault'
        tags: [ 'controller.service_arguments' ]

    Jmf\CrudEngine\Controller\UpdateAction:
        tags: [ 'controller.service_arguments' ]

    Jmf\CrudEngine\Loading\EntityRouteLoader:
        arguments:
            $loaders:
                - '@Jmf\CrudEngine\Loading\EntityCreateActionRouteLoader'
                - '@Jmf\CrudEngine\Loading\EntityDeleteActionRouteLoader'
                - '@Jmf\CrudEngine\Loading\EntityIndexActionRouteLoader'
                - '@Jmf\CrudEngine\Loading\EntityReadActionRouteLoader'
                - '@Jmf\CrudEngine\Loading\EntityUpdateActionRouteLoader'
