services:

    _defaults:
        autoconfigure: true
        autowire:      true

    Jmf\CrudEngine\:
        resource: '../src/'

    Jmf\CrudEngine\Controller\CreateAction:
        arguments:
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\Helpers\CreateActionHelperDefault'

    Jmf\CrudEngine\Controller\DeleteAction:
        arguments:
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\Helpers\DeleteActionHelperDefault'

    Jmf\CrudEngine\Controller\IndexAction:
        arguments:
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\Helpers\IndexActionHelperDefault'

    Jmf\CrudEngine\Controller\ReadAction:
        arguments:
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\Helpers\ReadActionHelperDefault'

    Jmf\CrudEngine\Controller\UpdateAction:
        arguments:
            $defaultActionHelper: '@Jmf\CrudEngine\Controller\Helpers\UpdateActionHelperDefault'

    Jmf\CrudEngine\Routing\RouteLoader:
        arguments:
            $loaders:
                - '@Jmf\CrudEngine\Routing\CreateActionRouteLoader'
                - '@Jmf\CrudEngine\Routing\DeleteActionRouteLoader'
                - '@Jmf\CrudEngine\Routing\IndexActionRouteLoader'
                - '@Jmf\CrudEngine\Routing\ReadActionRouteLoader'
                - '@Jmf\CrudEngine\Routing\UpdateActionRouteLoader'
